spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/StyxCo/spring-cloud-config-git-repo-ecgw
  security:
    user:
      name: user
      password: masterkey

server:
  port: 8888
